version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - yourmenu-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmindata-dev:/var/lib/pgadmin/data
    depends_on:
      - postgres
    networks:
      - yourmenu-network

networks:
  yourmenu-network:
    driver: bridge

volumes:
  pgdata-dev:
    driver: local
  pgadmindata-dev:
    driver: local
