version: "3.7"

services:
  yourmenu:
    build:
      context: ..
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - yourmenu-network

  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - yourmenu-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - yourmenu-network

networks:
  yourmenu-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local
