CREATE TABLE dish_size_option
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size_option_id BIGINT                                  NOT NULL,
    dish_id        BIGINT                                  NOT NULL,
    price          DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_dishsizeoption PRIMARY KEY (id)
);

ALTER TABLE dish_size_option
    ADD CONSTRAINT FK_DISHSIZEOPTION_ON_DISH FOREIGN KEY (dish_id) REFERENCES dish (id);

ALTER TABLE dish_size_option
    ADD CONSTRAINT FK_DISHSIZEOPTION_ON_SIZEOPTION FOREIGN KEY (size_option_id) REFERENCES size_option (id);