CREATE TABLE orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id VARCHAR(255)                            NOT NULL,
    date_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    price         DECIMAL                                 NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);