CREATE TABLE order_item
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id            BIGINT,
    dish_size_option_id BIGINT,
    quantity            INTEGER                                 NOT NULL,
    price               DECIMAL                                 NOT NULL,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_DISH_SIZE_OPTION FOREIGN KEY (dish_size_option_id) REFERENCES dish_size_option (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);