CREATE TABLE restaurant_address
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id VARCHAR(255)                            NOT NULL,
    cep           numeric(8)                              NOT NULL,
    state         VARCHAR(255)                            NOT NULL,
    city          TEXT                                    NOT NULL,
    street        TEXT                                    NOT NULL,
    number        INTEGER,
    district      TEXT                                    NOT NULL,
    complement    TEXT,
    reference     TEXT,
    CONSTRAINT pk_restaurantaddress PRIMARY KEY (id)
);

ALTER TABLE restaurant_address
    ADD CONSTRAINT uc_restaurantaddress_restaurant UNIQUE (restaurant_id);

ALTER TABLE restaurant_address
    ADD CONSTRAINT FK_RESTAURANTADDRESS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);