CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE category
    ADD CONSTRAINT uc_9adfedef62119982e88edf47c UNIQUE (restaurant_id, name);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);