CREATE TABLE dish
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id VARCHAR(255),
    category_id   BIGINT,
    name          VARCHAR(255)                            NOT NULL,
    description   TEXT,
    is_available  BOOLEAN                                 NOT NULL,
    image_url     VARCHAR(255),
    CONSTRAINT pk_dish PRIMARY KEY (id)
);

ALTER TABLE dish
    ADD CONSTRAINT uc_84fd89af342f147017c243359 UNIQUE (restaurant_id, name);

ALTER TABLE dish
    ADD CONSTRAINT FK_DISH_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE dish
    ADD CONSTRAINT FK_DISH_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);