CREATE TABLE size_option
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value        VARCHAR(255)                            NOT NULL,
    measure_unit VARCHAR(255),
    CONSTRAINT pk_sizeoption PRIMARY KEY (id)
);